export enum RoleType {
  USER = 'USER',
  ADMIN = 'ADMIN',
  DRIVER = 'DRIVER',
  CONSUMER = 'CONSUMER',
  WAREHOUSE_MANAGER = 'WAREHOUSE_MANAGER',
  DISPATCHER = 'DISPATCHER',
  FLEET_MANAGER = 'FLEET_MANAGER',
  SUPPLIER = 'SUPPLIER',
  CUSTOMER_SUPPORT = 'CUSTOMER_SUPPORT',
  ALL = '*', // wildcard role
}
